---
- hosts: all
  gather_facts: no
  connection: local

  tasks:
   - name: turn on ip routing 
     cisco.ios.ios_config:
      lines: ip routing 

   - name: Change hostname, domain name, and add DNS server
     cisco.ios.ios_system:
       hostname: c3650-1
       domain_name: stbates.com
       name_servers: 
        - 198.18.133.1

   - name: Configure vlan 10 ip address 
     cisco.ios.ios_l3_interfaces:
      config:
      - name: vlan 10
        ipv4:
        - address: 192.168.10.1/24
      
        
   - name: Put vlan 10 on OSPF area 0
     cisco.ios.ios_ospf_interfaces:
      config:
      - name: vlan 10
        address_family:
          - afi: ipv4
            process:
              id: 1
              area_id: 0

   - name: Turn on vlan 10 interface
     cisco.ios.ios_interfaces:
       config:
       - name: vlan 10
         description: Configured and Merged by Ansible Network
         enabled: true

   - name: Turn on DHCP Snooping
     cisco.ios.ios_config:
      lines: 
        - ip dhcp snooping 
        - ip dhcp snooping vlan 10
        - no ip dhcp snooping information option

   - name: Configure NTP Config
     cisco.ios.ios_config:
      lines: 
        - ntp authenticate
        - ntp master 1
      #  - ntp server 10.1.17.201 prefer source

   - name: AAA and 802.1x
     cisco.ios.ios_config:
      lines: 
        - aaa new-model
        - dot1x system-auth-control

   - name: configure policer in Scavenger class
     cisco.ios.ios_config:
      lines:
        - tracking enable
      parents:
        - device-tracking policy aaa

   - name: AAA for Radius 
     cisco.ios.ios_config:
      lines:
        - server name ISE_RADIUS
      parents:
        - aaa group server radius ISE_RADIUS

   - name: AAA for Radius 
     cisco.ios.ios_config:
      lines:
        - client 10.1.17.245 server-key C!sco12345
        - auth-type any
      parents:
        - aaa server radius dynamic-author
   - name: AAA for Radius 
     cisco.ios.ios_config:
      lines:
        - address ipv4 10.1.17.245 auth-port 1812 acct-port 1813
        - pac key C!sco12345
      parents:
        - radius ISE_RADIUS
 
        


      
      

