---
- hosts: all
  gather_facts: no
  connection: local

  tasks:
   - name: turn on ip routing 
     cisco.ios.ios_config:
      lines: ip routing 

   - name: Change hostname, domain name, and add DNS server
     cisco.ios.ios_system:
       hostname: c3650-1
       domain_name: stbates.com
       name_servers: 
        - 10.1.17.201

   - name: Configure vlan 10 ip address 
     cisco.ios.ios_l3_interfaces:
      config:
      - name: vlan 10
        ipv4:
        - address: 192.168.10.1/24
      
        
   - name: Put vlan 10 on OSPF area 0
     cisco.ios.ios_ospf_interfaces:
      config:
      - name: vlan 10
        address_family:
          - afi: ipv4
            process:
              id: 1
              area_id: 0

   - name: Turn on vlan 10 interface
     cisco.ios.ios_interfaces:
       config:
       - name: vlan 10
         description: Configured and Merged by Ansible Network
         enabled: true

   - name: Turn on DHCP Snooping
     cisco.ios.ios_config:
      lines: 
        - ip dhcp snooping 
        - ip dhcp snooping vlan 10
        - no ip dhcp snooping information option

   - name: Configure NTP Config
     cisco.ios.ios_config:
      lines: 
        - ntp authenticate
        - ntp master 1
        - ntp server 10.1.17.201 prefer source

   - name: AAA and 802.1x
     cisco.ios.ios_config:
      lines: 
        - aaa new-model
        - dot1x system-auth-control

   - name: configure policer in Scavenger class
     cisco.ios.ios_config:
      lines:
        - tracking enable
      parents:
        - device-tracking policy aaa

   - name: AAA for Radius Part 1
     cisco.ios.ios_config:
      lines:
        - server name ISE_RADIUS
      parents:
        - aaa group server radius ISE_RADIUS

   - name: AAA for Radius Part 2
     cisco.ios.ios_config:
      lines:
        - client 10.1.17.245 server-key {{ radius_secret}}
        - auth-type any
      parents:
        - aaa server radius dynamic-author
   - name: AAA for Radius Part 3
     cisco.ios.ios_config:
      lines:
        - address ipv4 10.1.17.245 auth-port 1812 acct-port 1813
        - pac key {{ radius_secret}}
      parents:
        - radius server ISE_RADIUS


   - name: AAA for Radius Part 4
     cisco.ios.ios_config:
       lines:
         - ip radius source-interface gi1/0/2
         - aaa authentication dot1x default group ISE_RADIUS
         - aaa authorization network default group ISE_RADIUS
         - aaa authorization auth-proxy default group ISE_RADIUS
         - aaa accounting auth-proxy default start-stop group ISE_RADIUS
         - aaa accounting dot1x default start-stop group ISE_RADIUS
    
 
   - name: Configuring Trustsec Part 1
     cisco.ios.ios_config:
       lines:
         - aaa authorization network CTS group ISE_RADIUS
         - cts authorization list CTS
         - cts authorization list CTS
         - cts role-based enforcement
         - cts role-based enforcement vlan-list 10
         - no cts server test all enable 
         - exit


   - name: Configure Trustsec Part 2
     cisco.ios.ios_command:
       commands: cts credentials id c3650-1 password 12345678

   - name: Configure interfaces for Vlans
     cisco.ios.ios_config:
       lines:
         - description ISE dot1x Port
         - switchport access vlan 10
         - device-tracking attach-policy AAA
         - ip dhcp relay information trusted
         - ip access-group ACL_DEFAULT in
         - switchport host
         - authentication host-mode multi-auth
         - authentication open
         - authentication order dot1x
         - authentication priority dot1x
         - authentication port-control auto
         - authentication periodic
         - authentication violations restrict
         - dot1x pae authenticator 
         - spanning-tree bpduguard enable
       parents:
         - interface GigabitEthernet1/0/1


   - name: Add ip-helper to vlan 
     cisco.ios.ios_config:
       lines:
         - ip helper-address 10.1.17.201
       parents:
         - interface vlan 10
      

   - name: Configure Defualt ACL
     cisco.ios.ios_config:
       lines:
         - permit udp any eq bootpc any eq bootps
         - permit udp any any eq domain
         - permit icmp any any
         - deny ip any any
       parents:
         - ip access-list extended ACL_DEFAULT

 
 
        


      
      

